### PR TITLE
Added Project pre-processor to Activator

### PR DESCRIPTION
**Pull request by corruptmemory**
Analyzes projects before they are loaded to perform corrective actions
if possible.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Can this be tested using scripted or some such integration test?

**Comment by corruptmemory** [comment]
In principle yes.  As you can guess, in practice, no, we just didn't do that.

I manually tested using Play 2.4.x-based templates and Play 2.3.x-based templates.  I also verified with RP templates.

For the core logic in https://github.com/typesafehub/activator/blob/wip/project-preprocessor/ui/app/activator/ProjectPreprocessor.scala I don't need to even write a scripted test.  Just tests against the file system would be adequate.

To do a full test requires more than scripted, you'd need Selenium or some other browser-based automation because the file that gets updated is written via Javascript through the Activator server.  The full interaction requires Activator running.

Yeah, just lots of tedious manual testing is what we've done to date.

**Comment by eed3si9n** [comment]
Well, look ok to me then.

**Comment by henrikengstrom** [comment]
Test ran quickly on Windows and if it's working there it can make it anywhere :)
LGTM

**Comment by corruptmemory** [comment]
"Works on Windows" == "Works anywhere" -- made my day. :-)

**Pull request merged**
