### PR TITLE
Tutorial: Fix typography and add quizzes + video support

### PR DESCRIPTION
**Pull request by Warry**
screen shot 2015-02-19 at 17 26 01
screen shot 2015-02-19 at 17 26 53

### CODE REVIEW

**Comment by henrikengstrom** [comment]
Is this really supposed to go into master of Activator?

**Comment by Warry** [comment]
I can close the PR until the release

**Comment by havocp** [comment]
Yep, we should save this until after release.
quick spellcheck ;-) s/quizz/quiz/ s/exercice/exercise/

**Comment by Warry** [comment]
French spelling, damn it !

**Pull request closed without merging**
