### PR TITLE
Modified the app version in activator.bat

### PR DESCRIPTION
**Pull request by TakumiSakamoto**
Modified the app version in `activator.bat`

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @TakumiSakamoto,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by TakumiSakamoto** [comment]
Sorry for not signing. Now I signed the agreement.

**Comment by corruptmemory** [comment]
Thanks for the fix.  Appreciated.

**Comment by TakumiSakamoto** [comment]
Thank you for merging.

**Pull request merged**
