### PR TITLE
Prep for 1.3.8 release

### PR DESCRIPTION
**Pull request by corruptmemory**
* Updated to the name Lightbend
* Relevant URLs updated to lightbend.com
* Updated offline cache hash
* Upgraded to sbt 0.13.11
* Verified that Play 2.5 things basically work

### CODE REVIEW

**Comment by eed3si9n** [comment]
Which part contributed to the Play 2.5 fix?

**Comment by corruptmemory** [comment]
There are two parts:

Part 1 was submitted by @benmccann in this PR: https://github.com/typesafehub/activator/pull/1103
Part 2 was the need to move all the activator infrastructure to sbt 0.13.11 because what activator uses is what's bundled into the offline zip repo (for seed templates) and the upstream Play samples based on 2.5 all require 0.13.11 as the version of sbt.

**Comment by eed3si9n** [comment]
LGTM

**Comment by hywel-evans** [comment]
Cool.  When are you targeting a release?

**Pull request merged**
