### PR TITLE
IE11 fixes

### PR DESCRIPTION
**Pull request by Warry**

### CODE REVIEW

**Comment by Warry** [comment]
** I meant `DOMNodeInserted ` not `DOMAdded`

**Comment by Warry** [comment]
just fixed a bug: when there are many lines of logs that comes ones, it was "loosing" the scroll

**Comment by Warry** [comment]
Hold on.

**Comment by henrikengstrom** [comment]
What happened? I was just reviewing this. Is a new one on it's way?

**Comment by Warry** [comment]
@henrikengstrom sorry, realized that there was some cranky stuffs again. https://github.com/typesafehub/activator/pull/966

**Pull request closed without merging**
