### PR TITLE
Issue #1091 - Move scripts into bin folder, launcher into libexec.

### PR DESCRIPTION
**Pull request by marc0der**
* moves `activator` and `activator.bat` scripts out of base folder into `bin`
* moves activator launcher jar into `libexec`

### CODE REVIEW

**Comment by corruptmemory** [comment]
LGTM

**Comment by marc0der** [comment]
@corruptmemory @@henrikengstrom excellent thanks, so would one of you be able to hit that merge button please?

**Comment by marc0der** [comment]
@corruptmemory @henrikengstrom any news on getting this merged guys?

**Comment by henrikengstrom** [comment]
Sorry for the late response. I know that @corruptmemory is working on a new release and this will be merged before that for sure.

**Comment by marc0der** [comment]
Thank you!

**Pull request merged**
