### PR TITLE
IE11 fixes

### PR DESCRIPTION
**Pull request by Warry**

### CODE REVIEW

**Comment by Warry** [comment]
hold on..

**Comment by Warry** [comment]
Seems ok now.

**Comment by henrikengstrom** [comment]
Clickable icon (circle) left to a task is missing (build view).

**Comment by Warry** [comment]
Those ones?

**Comment by Warry** [comment]
Those ones?

screen shot 2015-01-21 at 17 30 50

**Comment by henrikengstrom** [comment]
Yes, these ones:
screen shot 2015-01-21 at 11 35 03

**Comment by henrikengstrom** [comment]
LGTM.

**Pull request merged**
